const WHOLE_DEPTH = 5;
const INDICATOR_OFFSET = 7;
const ANIMATION_DURATION = 300;
const INDICATOR_Y_OFFSET = -35;
const ICON_ACTIVE_SCALE = 1.2;
const ICON_INACTIVE_SCALE = 1;
const PATH_CURVE_OFFSET = 30;
const PATH_CONTROL_POINT_OFFSET = 12;
const PATH_CONTROL_POINT_Y = 20;

export {
  WHOLE_DEPTH,
  INDICATOR_OFFSET,
  ANIMATION_DURATION,
  INDICATOR_Y_OFFSET,
  ICON_ACTIVE_SCALE,
  ICON_INACTIVE_SCALE,
  PATH_CURVE_OFFSET,
  PATH_CONTROL_POINT_OFFSET,
  PATH_CONTROL_POINT_Y,
}